version: '2'
services:
    jhipsterapp1-app:
        image: jhipsterapp1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhipsterapp1-oracle:1521:jhipsterApp1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
